sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: SBxJXuebNDzPBruYO1Ls4scBbG2pJ3JNFMXLBttSnYor8PEvsQntL0Y5ad3PbUv1Z0gddbDCqDGgxYX5djsw1FGQHIPoma659L7aHYLmjgA/IKqosBZ5I6vXA8ImiL8JzDfz+rmTuFNC8lZATZvm/I9n8M0Jzfs42lIPvgRAR00jjy/xkcCKkCQ4z8Dkr8D0/QxKcKeYSRPKeN7GEfTAo2oLFAlMfmWdxB/tecMtnc11HULRQa6HDaMH1urpUL55qfmzf22XXbXO5j7ejMyec6fpawXJsmPcaUZzF6TcqpsnuTATqMxrYKw86nJBFUmWbjkO5mO6s6rqSXyvNOrThMEkQFaYLeOWWlCp8Uz4/CKf/QhI8D6+8f/QXNV6jmhZ9hVY7cTsKozLHol6f+mp7f+TnXXQpvLwPjDxBv+vg7tVrMXMvJEr3j9hTZIMNnEwlCXxtPGO42/ElJOt43w0AHZd6MYqyo8AceUk38SLFfA9OCKXPUhSorEuytz0NuYIVT9tixtW86rXZG5ZaSW2Poh5l75/kN4x6yS38fgYSq/QUVVqpaiJ7RQzYVzlvHhBfoJaLkCsHFjS+1ZyB8C32DmPyBAIr31HXYs64pdHwHb65JNkvxaO7sD0ukace0YxQZzr3p3WtiLFV7nmuaWZtl8fEZs9I1TFA0J5xr7FOyk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/In-the-Reign-of-Terror--The-Adventures-of-a-Westminster-Boy_3785
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy